-- College Feedback Management System - MySQL schema (import in phpMyAdmin)
-- Matches the ERD exactly. Seed demo data afterwards with:  npm run db:seed
CREATE DATABASE IF NOT EXISTS college CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE college ;
SET FOREIGN_KEY_CHECKS = 0;
CREATE TABLE departments(department_id INT AUTO_INCREMENT PRIMARY KEY, department_name VARCHAR(100) NOT NULL UNIQUE);
CREATE TABLE programmes(program_id INT AUTO_INCREMENT PRIMARY KEY, program_name VARCHAR(100) NOT NULL, dept_id INT NOT NULL, FOREIGN KEY(dept_id) REFERENCES departments(department_id));
CREATE TABLE faculty(faculty_id INT AUTO_INCREMENT PRIMARY KEY, faculty_name VARCHAR(100) NOT NULL, dept_id INT NOT NULL, email VARCHAR(120) NOT NULL UNIQUE, designation VARCHAR(80), FOREIGN KEY(dept_id) REFERENCES departments(department_id));
CREATE TABLE batches(batch_id INT AUTO_INCREMENT PRIMARY KEY, batch_name VARCHAR(80) NOT NULL, academic_year VARCHAR(20) NOT NULL, semester INT NOT NULL, program_id INT NOT NULL, FOREIGN KEY(program_id) REFERENCES programmes(program_id));
CREATE TABLE students(student_id INT AUTO_INCREMENT PRIMARY KEY, roll_no VARCHAR(30) NOT NULL UNIQUE, student_name VARCHAR(100) NOT NULL, email VARCHAR(120) NOT NULL UNIQUE);
CREATE TABLE enrollments(enrollment_id INT AUTO_INCREMENT PRIMARY KEY, student_id INT NOT NULL, batch_id INT NOT NULL, status ENUM('Active','Inactive') DEFAULT 'Active', UNIQUE(student_id,batch_id), FOREIGN KEY(student_id) REFERENCES students(student_id), FOREIGN KEY(batch_id) REFERENCES batches(batch_id));
CREATE TABLE courses(course_id INT AUTO_INCREMENT PRIMARY KEY, course_code VARCHAR(20) NOT NULL UNIQUE, course_name VARCHAR(120) NOT NULL, credits INT NOT NULL, semester INT NOT NULL);
CREATE TABLE course_offerings(offering_id INT AUTO_INCREMENT PRIMARY KEY, course_id INT NOT NULL, faculty_id INT NOT NULL, batch_id INT NOT NULL, academic_year VARCHAR(20), semester INT, FOREIGN KEY(course_id) REFERENCES courses(course_id), FOREIGN KEY(faculty_id) REFERENCES faculty(faculty_id), FOREIGN KEY(batch_id) REFERENCES batches(batch_id));
CREATE TABLE types_of_feedback(type_id INT AUTO_INCREMENT PRIMARY KEY, type_name VARCHAR(60) NOT NULL UNIQUE);
CREATE TABLE facilities(facility_id INT AUTO_INCREMENT PRIMARY KEY, facility_name VARCHAR(60) NOT NULL UNIQUE);
CREATE TABLE feedback_forms(feedback_id INT AUTO_INCREMENT PRIMARY KEY, offering_id INT NULL, feedback_title VARCHAR(150) NOT NULL, description TEXT, start_date DATE NOT NULL, end_date DATE NOT NULL, status ENUM('Draft','Published','Closed') DEFAULT 'Draft', feedback_types VARCHAR(60), audience_type ENUM('Student','Faculty','All') DEFAULT 'Student', sub_type VARCHAR(60), is_anonymous BOOLEAN DEFAULT TRUE, created_by INT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(offering_id) REFERENCES course_offerings(offering_id));
CREATE TABLE feedback_questions(question_id INT AUTO_INCREMENT PRIMARY KEY, feedback_id INT NOT NULL, question_text VARCHAR(300) NOT NULL, question_type ENUM('Rating','Text','Yes/No','Multiple Choice') NOT NULL, question_number INT NOT NULL, options VARCHAR(500), FOREIGN KEY(feedback_id) REFERENCES feedback_forms(feedback_id) ON DELETE CASCADE);
CREATE TABLE feedback_responses(response_id INT AUTO_INCREMENT PRIMARY KEY, feedback_id INT NOT NULL, question_id INT NOT NULL, student_id INT NULL, answer TEXT, submitted_date DATETIME DEFAULT CURRENT_TIMESTAMP, faculty_id INT NULL, respondent_type ENUM('Student','Faculty') NOT NULL, FOREIGN KEY(feedback_id) REFERENCES feedback_forms(feedback_id) ON DELETE CASCADE, FOREIGN KEY(question_id) REFERENCES feedback_questions(question_id) ON DELETE CASCADE);
-- Added: login accounts (role: Admin/Faculty/Student; ref_id = faculty_id / student_id)
CREATE TABLE users(user_id INT AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(100) NOT NULL, email VARCHAR(120) NOT NULL UNIQUE, password_hash VARCHAR(100) NOT NULL, role ENUM('Admin','Faculty','Student') NOT NULL, ref_id INT NULL, status ENUM('Active','Inactive') DEFAULT 'Active', created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
